### ISSUE TITLE
Srediti repozitorijum

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG181-ambar#1]
Obrisati fajlove koji se ne koriste. Smestiti teksture u zaseban direktorijum i promeniti putanje prilikom njihovog ucitavanja. Napraviti makefile, posto trenutni kod u README.md puca. 

Ubaciti screenshot-ove projekta u zaseban direktorijum.

U README.md treba da stoji kratak opis projekta, opis pokretanja projekta (npr. koriscenjem makefile-a), sve bilblioteke koje su koriscene kao i kratko uputstvo kako ih instalirati.

**Comment by VeraV3** [comment]
Obrisala sam fajlove, smestila teksture u zaseban direktorijum, napravila makefile, ubacila screenshot-ove i prepravila README.md fajl.
